// 五行主题色定义 — 按日主天干映射
// 木(甲乙) 火(丙丁) 土(戊己) 金(庚辛) 水(壬癸)

var THEMES = {
  // ===== 木 — 甲乙 =====
  '甲': {
    name: '木', element: 'wood',
    primary: '#2E7D32',
    accent: '#4CAF50',
    bg: '#F1F8E9',
    border: '#C8E6C9',
    highlight: '#E8F5E9',
    gradient: 'linear-gradient(135deg, #2E7D32, #1B5E20)',
    text: '#1B5E20',
    btnText: '#FFFFFF',
    cardBg: '#FFFFFF',
    tagBg: '#E8F5E9',
    yiColor: '#2E7D32',
    jiColor: '#C62828',
    bodyText: '#2E3B2E',
    subText: '#7A9B7A',
    mutedText: '#B0C8B0',
    navBg: '#1B5E20',
    navTextStyle: 'white',
    cardGradient: 'linear-gradient(135deg, #F1F8E9, #E8F5E9)',
    divider: '#C8E6C9',
    tabBarBg: '#F1F8E9',
    tabBarSelected: '#2E7D32',
    tabBarNormal: '#7A9B7A',
    tabBarBorder: '#C8E6C9',
    infoCardBg: '#F1F8E9',
    clashBg: '#E8F5E9',
    clashText: '#2E7D32',
    heroGradient: 'linear-gradient(135deg, #F1F8E9, #E8F5E9)'
  },
  '乙': {
    name: '木', element: 'wood',
    primary: '#388E3C',
    accent: '#66BB6A',
    bg: '#F1F8E9',
    border: '#C8E6C9',
    highlight: '#E8F5E9',
    gradient: 'linear-gradient(135deg, #388E3C, #2E7D32)',
    text: '#1B5E20',
    btnText: '#FFFFFF',
    cardBg: '#FFFFFF',
    tagBg: '#E8F5E9',
    yiColor: '#2E7D32',
    jiColor: '#C62828',
    bodyText: '#2E3B2E',
    subText: '#7A9B7A',
    mutedText: '#B0C8B0',
    navBg: '#2E7D32',
    navTextStyle: 'white',
    cardGradient: 'linear-gradient(135deg, #F1F8E9, #E8F5E9)',
    divider: '#C8E6C9',
    tabBarBg: '#F1F8E9',
    tabBarSelected: '#388E3C',
    tabBarNormal: '#7A9B7A',
    tabBarBorder: '#C8E6C9',
    infoCardBg: '#F1F8E9',
    clashBg: '#E8F5E9',
    clashText: '#2E7D32',
    heroGradient: 'linear-gradient(135deg, #F1F8E9, #E8F5E9)'
  },

  // ===== 火 — 丙丁 =====
  '丙': {
    name: '火', element: 'fire',
    primary: '#C41E1E',
    accent: '#DAA520',
    bg: '#FFF8DC',
    border: '#E0D5C0',
    highlight: '#FFF0F0',
    gradient: 'linear-gradient(135deg, #C41E1E, #8B0000)',
    text: '#8B0000',
    btnText: '#FFFFFF',
    cardBg: '#FFFFFF',
    tagBg: '#FDE8E8',
    yiColor: '#2E7D32',
    jiColor: '#C41E1E',
    bodyText: '#4A3333',
    subText: '#9B8B7B',
    mutedText: '#C8BDB0',
    navBg: '#8B0000',
    navTextStyle: 'white',
    cardGradient: 'linear-gradient(135deg, #FFFBF5, #FFF5F0)',
    divider: '#E0D5C0',
    tabBarBg: '#FFF8DC',
    tabBarSelected: '#C41E1E',
    tabBarNormal: '#9B8B7B',
    tabBarBorder: '#E0D5C0',
    infoCardBg: '#FFFBF5',
    clashBg: '#FFF8E1',
    clashText: '#B8860B',
    heroGradient: 'linear-gradient(135deg, #FFFBF5, #FFF8F0)'
  },
  '丁': {
    name: '火', element: 'fire',
    primary: '#D32F2F',
    accent: '#FFC107',
    bg: '#FFF8DC',
    border: '#E0D5C0',
    highlight: '#FFF0F0',
    gradient: 'linear-gradient(135deg, #D32F2F, #B71C1C)',
    text: '#B71C1C',
    btnText: '#FFFFFF',
    cardBg: '#FFFFFF',
    tagBg: '#FDE8E8',
    yiColor: '#2E7D32',
    jiColor: '#C41E1E',
    bodyText: '#4A3333',
    subText: '#9B8B7B',
    mutedText: '#C8BDB0',
    navBg: '#B71C1C',
    navTextStyle: 'white',
    cardGradient: 'linear-gradient(135deg, #FFFBF5, #FFF5F0)',
    divider: '#E0D5C0',
    tabBarBg: '#FFF8DC',
    tabBarSelected: '#D32F2F',
    tabBarNormal: '#9B8B7B',
    tabBarBorder: '#E0D5C0',
    infoCardBg: '#FFFBF5',
    clashBg: '#FFF8E1',
    clashText: '#B8860B',
    heroGradient: 'linear-gradient(135deg, #FFFBF5, #FFF8F0)'
  },

  // ===== 土 — 戊己 =====
  '戊': {
    name: '土', element: 'earth',
    primary: '#E65100',
    accent: '#FF9800',
    bg: '#FFFDE7',
    border: '#FFE0B2',
    highlight: '#FFF3E0',
    gradient: 'linear-gradient(135deg, #E65100, #BF360C)',
    text: '#BF360C',
    btnText: '#FFFFFF',
    cardBg: '#FFFFFF',
    tagBg: '#FFF3E0',
    yiColor: '#2E7D32',
    jiColor: '#C62828',
    bodyText: '#4A3528',
    subText: '#9B8B70',
    mutedText: '#C8BDA0',
    navBg: '#BF360C',
    navTextStyle: 'white',
    cardGradient: 'linear-gradient(135deg, #FFFDE7, #FFF8E1)',
    divider: '#FFE0B2',
    tabBarBg: '#FFFDE7',
    tabBarSelected: '#E65100',
    tabBarNormal: '#9B8B70',
    tabBarBorder: '#FFE0B2',
    infoCardBg: '#FFFDE7',
    clashBg: '#FFF3E0',
    clashText: '#E65100',
    heroGradient: 'linear-gradient(135deg, #FFFDE7, #FFF8E1)'
  },
  '己': {
    name: '土', element: 'earth',
    primary: '#EF6C00',
    accent: '#FFA726',
    bg: '#FFFDE7',
    border: '#FFE0B2',
    highlight: '#FFF3E0',
    gradient: 'linear-gradient(135deg, #EF6C00, #E65100)',
    text: '#BF360C',
    btnText: '#FFFFFF',
    cardBg: '#FFFFFF',
    tagBg: '#FFF3E0',
    yiColor: '#2E7D32',
    jiColor: '#C62828',
    bodyText: '#4A3528',
    subText: '#9B8B70',
    mutedText: '#C8BDA0',
    navBg: '#E65100',
    navTextStyle: 'white',
    cardGradient: 'linear-gradient(135deg, #FFFDE7, #FFF8E1)',
    divider: '#FFE0B2',
    tabBarBg: '#FFFDE7',
    tabBarSelected: '#EF6C00',
    tabBarNormal: '#9B8B70',
    tabBarBorder: '#FFE0B2',
    infoCardBg: '#FFFDE7',
    clashBg: '#FFF3E0',
    clashText: '#E65100',
    heroGradient: 'linear-gradient(135deg, #FFFDE7, #FFF8E1)'
  },

  // ===== 金 — 庚辛 =====
  '庚': {
    name: '金', element: 'metal',
    primary: '#455A64',
    accent: '#90A4AE',
    bg: '#ECEFF1',
    border: '#CFD8DC',
    highlight: '#ECEFF1',
    gradient: 'linear-gradient(135deg, #455A64, #263238)',
    text: '#263238',
    btnText: '#FFFFFF',
    cardBg: '#FFFFFF',
    tagBg: '#ECEFF1',
    yiColor: '#2E7D32',
    jiColor: '#C62828',
    bodyText: '#37474F',
    subText: '#90A4AE',
    mutedText: '#B0BEC5',
    navBg: '#263238',
    navTextStyle: 'white',
    cardGradient: 'linear-gradient(135deg, #ECEFF1, #E0E5E8)',
    divider: '#CFD8DC',
    tabBarBg: '#ECEFF1',
    tabBarSelected: '#455A64',
    tabBarNormal: '#90A4AE',
    tabBarBorder: '#CFD8DC',
    infoCardBg: '#ECEFF1',
    clashBg: '#ECEFF1',
    clashText: '#455A64',
    heroGradient: 'linear-gradient(135deg, #ECEFF1, #E0E5E8)'
  },
  '辛': {
    name: '金', element: 'metal',
    primary: '#546E7A',
    accent: '#B0BEC5',
    bg: '#ECEFF1',
    border: '#CFD8DC',
    highlight: '#ECEFF1',
    gradient: 'linear-gradient(135deg, #546E7A, #37474F)',
    text: '#263238',
    btnText: '#FFFFFF',
    cardBg: '#FFFFFF',
    tagBg: '#ECEFF1',
    yiColor: '#2E7D32',
    jiColor: '#C62828',
    bodyText: '#37474F',
    subText: '#90A4AE',
    mutedText: '#B0BEC5',
    navBg: '#37474F',
    navTextStyle: 'white',
    cardGradient: 'linear-gradient(135deg, #ECEFF1, #E0E5E8)',
    divider: '#CFD8DC',
    tabBarBg: '#ECEFF1',
    tabBarSelected: '#546E7A',
    tabBarNormal: '#90A4AE',
    tabBarBorder: '#CFD8DC',
    infoCardBg: '#ECEFF1',
    clashBg: '#ECEFF1',
    clashText: '#455A64',
    heroGradient: 'linear-gradient(135deg, #ECEFF1, #E0E5E8)'
  },

  // ===== 水 — 壬癸 =====
  '壬': {
    name: '水', element: 'water',
    primary: '#0D47A1',
    accent: '#42A5F5',
    bg: '#E3F2FD',
    border: '#BBDEFB',
    highlight: '#E3F2FD',
    gradient: 'linear-gradient(135deg, #0D47A1, #01579B)',
    text: '#01579B',
    btnText: '#FFFFFF',
    cardBg: '#FFFFFF',
    tagBg: '#E3F2FD',
    yiColor: '#2E7D32',
    jiColor: '#C62828',
    bodyText: '#1A2B3C',
    subText: '#7B9BB8',
    mutedText: '#A8C8E0',
    navBg: '#01579B',
    navTextStyle: 'white',
    cardGradient: 'linear-gradient(135deg, #E3F2FD, #BBDEFB)',
    divider: '#BBDEFB',
    tabBarBg: '#E3F2FD',
    tabBarSelected: '#0D47A1',
    tabBarNormal: '#7B9BB8',
    tabBarBorder: '#BBDEFB',
    infoCardBg: '#E3F2FD',
    clashBg: '#E3F2FD',
    clashText: '#0D47A1',
    heroGradient: 'linear-gradient(135deg, #E3F2FD, #BBDEFB)'
  },
  '癸': {
    name: '水', element: 'water',
    primary: '#1565C0',
    accent: '#64B5F6',
    bg: '#E3F2FD',
    border: '#BBDEFB',
    highlight: '#E3F2FD',
    gradient: 'linear-gradient(135deg, #1565C0, #0D47A1)',
    text: '#01579B',
    btnText: '#FFFFFF',
    cardBg: '#FFFFFF',
    tagBg: '#E3F2FD',
    yiColor: '#2E7D32',
    jiColor: '#C62828',
    bodyText: '#1A2B3C',
    subText: '#7B9BB8',
    mutedText: '#A8C8E0',
    navBg: '#0D47A1',
    navTextStyle: 'white',
    cardGradient: 'linear-gradient(135deg, #E3F2FD, #BBDEFB)',
    divider: '#BBDEFB',
    tabBarBg: '#E3F2FD',
    tabBarSelected: '#1565C0',
    tabBarNormal: '#7B9BB8',
    tabBarBorder: '#BBDEFB',
    infoCardBg: '#E3F2FD',
    clashBg: '#E3F2FD',
    clashText: '#0D47A1',
    heroGradient: 'linear-gradient(135deg, #E3F2FD, #BBDEFB)'
  }
};

// 默认主题（无八字时使用传统火色系）
var DEFAULT_THEME = THEMES['丙'];

// 根据日主天干获取主题
function getTheme(dayMaster) {
  if (dayMaster && THEMES[dayMaster]) {
    return THEMES[dayMaster];
  }
  return DEFAULT_THEME;
}

// 获取所有10天干的主题映射
function getThemeByStem() {
  return THEMES;
}

module.exports = {
  THEMES: THEMES,
  DEFAULT_THEME: DEFAULT_THEME,
  getTheme: getTheme,
  getThemeByStem: getThemeByStem
};
